### ISSUE TITLE
Errors thrown when resizing box

### ISSUE THREAD

**Issue by olivergeorge** [condense/openlayers-om-components#3]
```
scaleinteraction.js:363 Uncaught TypeError: undefined is not a functionscale
interaction.js:363 (anonymous function)
array.js:202 goog.array.forEach.goog.NATIVE_ARRAY_PROTOTYPES.
...
```

**Comment by olivergeorge** [comment]
I believe the problem was introduced here: a93a7613

**Comment by ul** [comment]
The problem was not introduced, but uncovered by mentioned commit. I have put files from original OL3 Scale & Translate interactions PRs, some of them were overriding modules from cljsjs/openlayers. But for somewhat reason override is forced with `:libs` compiler option in `project.clj`, but not with one in `deps.cljs`.

To fix the problem I modified overriding files to make them as separate modules with own namespaces and required them in `scaleinteraction.js` explicitly.
